# Generated by Django 4.0.5 on 2022-07-03 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papers_app', '0002_question_creater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpaper',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='checked_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='checker_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='examined_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='examiner_review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
