# Generated by Django 3.2.7 on 2022-07-15 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papers_app', '0003_alter_testpaper_checker_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testpaper',
            old_name='is_approved',
            new_name='is_checker_approved',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_type',
            field=models.CharField(blank=True, choices=[('TEXT', 'text_type'), ('IMAGE', 'image_type'), ('AUDIO', 'audio_type')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_delete',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testpaper',
            name='cut_0ff_marks',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testpaper',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='is_examinar_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_choice', models.CharField(choices=[('SETTER', 'Setter'), ('EXAMINAR', 'Examinar'), ('CHECKER', 'Checker')], max_length=10)),
                ('mobile_number', models.CharField(max_length=12)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers_app.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckingTestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checker_review', models.TextField(blank=True, null=True)),
                ('is_checker_approved', models.BooleanField(default=False)),
                ('test_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_check', to='papers_app.testpaper')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedTestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examiner_review', models.TextField(blank=True, null=True)),
                ('is_examiner_approved', models.BooleanField(default=False)),
                ('test_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_approve', to='papers_app.testpaper')),
            ],
        ),
    ]
