# Generated by Django 4.0.6 on 2022-07-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers_app', '0004_auto_20220715_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testpaper',
            old_name='cut_0ff_marks',
            new_name='cut_off_marks',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='is_sent_for_cheeck',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_choice',
            field=models.CharField(choices=[(0, 'Setter'), (2, 'Examinar'), (1, 'Checker')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='papers_app.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='questions',
            field=models.ManyToManyField(default=[], to='papers_app.question'),
        ),
    ]
